//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examples.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sampledata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sampledata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Examples.Tests.Sampledata", typeof(Sampledata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;vehicles&gt;
        ///	&lt;planes&gt;
        ///		&lt;plane&gt;
        ///			&lt;name&gt;Boeing 747&lt;/name&gt;
        ///			&lt;cost&gt;$24 million&lt;/cost&gt;
        ///			&lt;passengers&gt;524&lt;/passengers&gt;
        ///			&lt;engines&gt;2&lt;/engines&gt;
        ///			&lt;manufacturer&gt;Boeing&lt;/manufacturer&gt;
        ///		&lt;/plane&gt;
        ///	&lt;/planes&gt;
        ///	&lt;cars&gt;
        ///		&lt;car&gt;
        ///			&lt;name&gt;Accord&lt;/name&gt;
        ///			&lt;cost&gt;$20,000&lt;/cost&gt;
        ///			&lt;passengers&gt;5&lt;/passengers&gt;
        ///			&lt;wheels&gt;4&lt;/wheels&gt;
        ///			&lt;manufacturer&gt;Honda&lt;/manufacturer&gt;
        ///		&lt;/car&gt;
        ///		&lt;car&gt;
        ///			&lt;name&gt;BMW 5 Series&lt;/name&gt;
        ///			&lt;cost&gt;$40,000&lt;/cost&gt;
        ///			&lt;passengers&gt;4&lt;/passengers&gt;
        ///			&lt;wheels&gt;4&lt;/wheels&gt;
        ///			&lt;manufac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	planes:[
        ///		{
        ///			name: &quot;Boeing 747&quot;,
        ///			cost: &quot;$24 million&quot;,
        ///			passengers: 524,
        ///			engines: 2,
        ///			manufacturer: &quot;Boeing&quot;,
        ///		}
        ///	],
        ///	cars:[
        ///		{
        ///			name: &quot;Accord&quot;,
        ///			cost: &quot;$20,000&quot;,
        ///			passengers: 5,
        ///			wheels: 4,
        ///			manufacturer: &quot;Honda&quot;,
        ///		},
        ///		{
        ///			name: &quot;BMW 5 Series&quot;,
        ///			cost: &quot;$40,000&quot;,
        ///			passengers: 4,
        ///			wheels: 4,
        ///			manufacturer: &quot;BMW&quot;,
        ///		}
        ///	]
        ///}.
        /// </summary>
        internal static string VehiclesJson {
            get {
                return ResourceManager.GetString("VehiclesJson", resourceCulture);
            }
        }
    }
}
